#!/usr/bin/env python3
"""Refresh src/data/rosters-<season>.js from ESPN's current team rosters.

ESPN serves only TODAY's roster, so this is a snapshot: re-run it during the season
and the cards follow signings, cuts and injured reserve. Same shape as rosters-2025.js.

  python3 tools/fetch_rosters.py 2026
"""
import json, os, subprocess, sys
from concurrent.futures import ThreadPoolExecutor

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
TEAMS = 'https://site.api.espn.com/apis/site/v2/sports/football/nfl/teams'
ROSTER = 'https://site.api.espn.com/apis/site/v2/sports/football/nfl/teams/%s/roster'
ALIAS = {'WSH': 'WAS', 'LA': 'LAR', 'JAC': 'JAX'}
UNITS = ('offense', 'defense', 'specialTeam', 'injuredReserveOrOut')   # practice squad left out


def get(url):
    # curl, not urllib: ESPN 403s Python's default client
    out = subprocess.run(['curl', '-s', '--max-time', '30', url],
                         capture_output=True, text=True).stdout
    return json.loads(out) if out.strip() else {}


def roster(tid):
    d = get(ROSTER % tid)
    c = (d.get('coach') or [{}])[0]
    players = []
    for grp in d.get('athletes', []):
        if grp.get('position') not in UNITS:
            continue
        for a in grp.get('items', []):
            players.append({
                'id': str(a['id']), 'n': a.get('displayName'), 'j': a.get('jersey'),
                'pos': (a.get('position') or {}).get('abbreviation'), 'u': grp['position'],
                'age': a.get('age'), 'ht': a.get('displayHeight'), 'wt': a.get('displayWeight'),
                'col': (a.get('college') or {}).get('name'),
                'exp': (a.get('experience') or {}).get('years'),
                'st': (a.get('status') or {}).get('name'),
            })
    coach = f"{c.get('firstName', '')} {c.get('lastName', '')}".strip() or None
    return {'coach': coach, 'count': len(players), 'players': players}


def main(season):
    ids = {}
    for lg in get(TEAMS).get('sports', [{}])[0].get('leagues', []):
        for t in lg.get('teams', []):
            t = t['team']
            ids[ALIAS.get(t['abbreviation'], t['abbreviation'])] = t['id']
    with ThreadPoolExecutor(max_workers=8) as ex:
        out = dict(zip(ids, ex.map(roster, ids.values())))
    bad = [k for k, v in out.items() if not v['count']]
    # Fail loudly rather than ship cards with empty rosters
    if len(out) != 32 or bad:
        print(f'roster pull incomplete: {len(out)} teams, empty {bad} — not writing', file=sys.stderr)
        sys.exit(1)
    p = os.path.join(ROOT, f'src/data/rosters-{season}.js')
    with open(p, 'w') as f:
        f.write(f'// Compact {season} rosters keyed by team ABBR. Photo id = ESPN headshot id.\n'
                '// Generated by tools/fetch_rosters.py (a snapshot of ESPN\'s current rosters).\n')
        f.write(f'export const ROSTERS{season} = '
                + json.dumps(dict(sorted(out.items())), separators=(',', ':'), ensure_ascii=False) + '\n')
    print(f'{len(out)} rosters, {sum(v["count"] for v in out.values())} players -> {os.path.relpath(p, ROOT)}')


main(sys.argv[1] if len(sys.argv) > 1 else '2026')
