#!/usr/bin/env python3
"""Refresh src/data/fpi-2026.js from ESPN's Football Power Index.

FPI is ESPN's team rating: the points a team would beat an average opponent by on a
neutral field. The tower uses it to say how hard each team's REMAINING schedule is --
the average rating of the opponents still to play, adjusted for where the game is.

ESPN publishes its own "remaining schedule" ranking alongside FPI, but only the rank,
never the number behind it. So we take the ratings and do the sum ourselves: that gives
a value per team and a difficulty per game, and ESPN's rank is kept as a check on it.

  python3 tools/fetch_fpi.py            # write
  python3 tools/fetch_fpi.py --dry-run  # report only
"""
import json, subprocess, sys, os

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
OUT = os.path.join(ROOT, 'src/data/fpi-2026.js')
SEASON = 2026

FPI = (f'https://sports.core.api.espn.com/v2/sports/football/leagues/nfl/seasons/'
       f'{SEASON}/powerindex?limit=40')
TEAMS = 'https://site.api.espn.com/apis/site/v2/sports/football/nfl/teams'

# ESPN abbreviation -> our schedule key (same map as update_results.py)
ALIAS = {'WSH': 'WAS', 'LA': 'LAR', 'JAC': 'JAX'}


def get(url):
    # curl, not urllib: ESPN 403s Python's default client
    out = subprocess.run(['curl', '-s', '--max-time', '30', url],
                         capture_output=True, text=True).stdout
    return json.loads(out) if out.strip() else {}


def main():
    dry = '--dry-run' in sys.argv

    # ESPN team id -> our abbreviation
    ids = {}
    for lg in get(TEAMS).get('sports', [{}])[0].get('leagues', []):
        for t in lg.get('teams', []):
            t = t['team']
            ids[str(t['id'])] = ALIAS.get(t['abbreviation'], t['abbreviation'])

    d = get(FPI)
    teams, updated = {}, None
    for it in d.get('items', []):
        tid = it['team']['$ref'].split('/teams/')[1].split('?')[0]
        ab = ids.get(tid)
        p = {s['name']: s.get('value') for s in it.get('predictives', [])}
        if ab is None or p.get('fpi') is None:
            continue
        teams[ab] = {
            'fpi': round(p['fpi'], 2),
            'rank': int(p['fpirank']) if p.get('fpirank') is not None else None,
            # ESPN's own remaining-schedule rank (1 = hardest), kept to check our sums
            'espnSosRem': int(p['sosremainingrank']) if p.get('sosremainingrank') is not None else None,
        }
        updated = it.get('lastUpdated') or updated

    # Fail loudly rather than ship a half-empty rating table
    if len(teams) != 32:
        print(f'FPI pull incomplete: {len(teams)} teams (expected 32) — not writing',
              file=sys.stderr)
        sys.exit(1)

    out = {'updated': updated, 'teams': dict(sorted(teams.items()))}
    for ab, t in sorted(teams.items(), key=lambda kv: kv[1]['rank'] or 99):
        print(f"  {t['rank']:>2}. {ab:4} FPI {t['fpi']:+6.2f}   ESPN remaining-schedule rank {t['espnSosRem']}")
    print(f'\n  ESPN last updated {updated}')

    if dry:
        print('--dry-run: nothing written')
        return
    with open(OUT, 'w') as f:
        f.write('// ESPN Football Power Index for 2026, one rating per team (points vs an average\n'
                '// opponent on a neutral field). Generated by tools/fetch_fpi.py -- the tower\n'
                '// computes each team\'s remaining-schedule difficulty from these.\n')
        f.write('export const FPI2026 = ' + json.dumps(out, separators=(',', ':')) + '\n')
    print(f'wrote {os.path.relpath(OUT, ROOT)}')


main()
